//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rozproszone_bazy_danych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int Province_Id { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
