//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rozproszone_bazy_danych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3946454639324231
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string SureName { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public double Last_energy_usage { get; set; }
        public Nullable<double> Pesel { get; set; }
        public int City_Id { get; set; }
        public string PasswordSalt { get; set; }
    }
}
