//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rozproszone_bazy_danych.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Users
    {
        public Users()
        {
            this.Settlement = new HashSet<Settlement>();
        }
    
        public int Id { get; set; }
        [DisplayName("Nazwa użytkownika")]
        [Required]
        [StringLength(100)]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Hasło")]
        [Required]
        [StringLength(100)]
        public string Password { get; set; }

        [DisplayName("Imię")]
        [Required]
        [StringLength(100)]
        public string FirstName { get; set; }

        [DisplayName("Nazwisko")]
        [Required]
        [StringLength(100)]
        public string SureName { get; set; }

        [DisplayName("Adres email")]
        [Required]
        [StringLength(100)]
        public string Mail { get; set; }

        [DisplayName("Nr telefonu")]
        [Required]
        [StringLength(10)]
        public string Phone { get; set; }

        [DisplayName("Aktualne zużycie energii")]
        public double Last_energy_usage { get; set; }

        [DisplayName("Nr PESEL")]
        [Required]
        public Nullable<double> Pesel { get; set; }

        [DisplayName("Miasto")]
        public int City_Id { get; set; }
        public string PasswordSalt { get; set; }
        public int UserRole { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
    }
}
